server:
  port: 2012
  servlet:
    context-path: /data
spring:
  profiles: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useSSL=false
    username: root
    password: P@ssw0rd
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
